project:
  type: website
  output-dir: docs

website:
  title: "Elise Gonzales"
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css
    toc: true

editor: visual

